[package]
name = "iroh-proxy"
version = "0.2.3"
edition = "2024"
rust-version = "1.91"
repository = "https://github.com/prekucki/iroh-proxy"
authors = ["prekucki"]

[package.metadata.wix]
upgrade-guid = "1B4E2EF4-94F0-40DA-88A9-2FB23B0BAF8E"
path-guid = "9AA904A2-6922-4388-A181-754AC31A4F1A"
license = false
eula = false

[dependencies]
anyhow = "1"
clap = { version = "4", features = ["derive"] }
crossterm = "0.28"
directories = "5"
futures-util = "0.3"
iroh = "1.0.3"
iroh-mainline-address-lookup = "0.4.0"
iroh-mdns-address-lookup = "0.4.0"
ratatui = "0.29"
serde = { version = "1", features = ["derive"] }
tokio = { version = "1", features = ["macros", "rt-multi-thread", "net", "io-util", "signal"] }
toml = "0.8"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }

[target.'cfg(not(windows))'.dependencies]
zbus = { version = "5", features = ["tokio", "p2p"] }

[target.'cfg(unix)'.dependencies]
libc = "0.2"

[target.'cfg(windows)'.dependencies]
uds_windows = "1"
zbus = { version = "5", features = ["p2p"] }

# The profile that 'dist' will build with
[profile.dist]
inherits = "release"
lto = "thin"
